<?php

/**
 * @file
 * Shows the www.idokep.hu heat map image in a block for Hungary.
 *
 * This module provides an easy way to show the freely
 * available Hungarian www.idokep.hu heat map in a block.
 */

/**
 * Implements hook_block_info().
 */
function weatherpic_block_info() {
  $block = array();
  $block['weatherpic'] = array(
    'info' => t('Weather Pic'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $block;
}

/**
 * Implements hook_block_configure().
 */
function weatherpic_block_configure($delta) {
  $form = array();
  if ($delta == 'weatherpic') {
    $options = array(
      1 => t('Budapest smog map'),
      2 => t('Clouds map'),
      3 => t('Animated clouds map'),
      4 => t('Heat map'),
      5 => t('UV map'),
      6 => t('Wind map'),
      7 => t('Animated wind map'),
      8 => t('Forecast bar'),
    );
    $form['weatherpics'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Weather images'),
      '#default_value' => variable_get('weatherpics', array()),
      '#options' => $options,
      '#description' => t('With these checkboxes you can customize which images to show in the block.'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function weatherpic_block_save($delta, $edit = array()) {
  if($delta == 'weatherpic') {
    variable_set('weatherpics', $edit['weatherpics']);
  }
  return;
}

/**
 * Implements hook_block_view().
 */
function weatherpic_block_view($delta) {
  if ($delta == 'weatherpic') {
    $content = '';
    $link = array();
    $weatherpics = variable_get('weatherpics');
    foreach ($weatherpics as $tmp) {
      if ($tmp != 0) {
        switch ($tmp) {
          case 1:
            $link[] = 'http://terkep.idokep.hu/kis_bp_szenny.jpg';
            $alt[] = t('Budapest smog map');
            break;
          case 2:
            $link[] = 'http://terkep.idokep.hu/terkep/hu/wap_idokep.jpg';
            $alt[] = t('Clouds map');
            break;
          case 3:
            $link[] = 'http://terkep.idokep.hu/terkep/hu/i_anim.gif';
            $alt[] = t('Animated clouds map');
            break;
          case 4:
            $link[] = 'http://terkep.idokep.hu/terkep/hu/hom_kozepes.jpg';
            $alt[] = t('Heat map');
            break;
          case 5:
            $link[] = 'http://terkep.idokep.hu/terkep/hu_mini/uvfeny_small.jpg';
            $alt[] = t('UV map');
            break;
          case 6:
            $link[] = 'http://terkep.idokep.hu/terkep/hu/wap_szelterkep.jpg';
            $alt[] = t('Wind map');
            break;
          case 7:
            $link[] = 'http://terkep.idokep.hu/terkep/hu/s_anim.gif';
            $alt[] = t('Animated wind map');
            break;
          case 8:
            $link[] = 'http://www.idokep.hu/hosszutavu_elore.jpg';
            $alt[] = t('Forecast bar');
            break;
          default:
            $content = '';
            break;
        }
      }
    }
    $length = count($link);
    if ($length > 0) {
      for ($i = 0; $i < $length; $i++) {
        $content .= l('<img src="' . $link[$i] . '" alt="' . $alt[$i] . '">', 'http://www.idokep.hu', array('html' => TRUE));
      }
      $content .= '<br>' . t('source: ') . l(t('idokep.hu'), 'http://www.idokep.hu');
    }
    $block = array(
      'subject' => t('Weather Pic'),
      'content' => $content,
    );
    return $block;
  }
}
